#!/bin/sh

set -eu

# creating kolibri user if it isn't already there
if ! getent passwd kolibri >/dev/null; then
        adduser --system --force-badname --quiet \
            --no-create-home \
            --home /var/lib/kolibri \
            --shell /sbin/nologin \
            --group \
            kolibri
fi

# create /var/lib/kolibri or set ownership for existing directory
if [ -d /var/lib/kolibri ]; then
	chown -R kolibri:kolibri /var/lib/kolibri
else
	install -d -m0755 -o kolibri -g kolibri /var/lib/kolibri
fi

#DEBHELPER#

exit 0

